version: '3.8'
services:
  api:
    build:
      context: "./sercer"
      dockerfile: "Dockerfile.dev"
    command: sh -c "yarn install && yarn start"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_LOGIN_URL=postgres://postgres:secret@db/postgres
    ports:
      - '4000:4000'
    working_dir: /app
    volumes:
      - ./api:/app:cached