version: '3.8'
services:
  server:
    build:
      context: "./server"
      dockerfile: "Dockerfile"
    # command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=4000
    ports:
      - '4000:4000'
    working_dir: /app
    volumes:
      - ./server:/app
      - ./server/node_modules
    networks:
      - node-network
  client:
    build:
      context: "./client"
      dockerfile: "Dockerfile"
    # command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - ./client:/app
      - ./client/node_modules
    networks:
      - node-network
      
networks:
  node-network:
    driver: bridge
