apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: goodgame-test
build:
  googleCloudBuild:
    projectId: goodgamestudiotest
  artifacts:
  - image: us.gcr.io/goodgamestudiotest/client
    context: client
    docker:
      dockerfile: Dockerfile.prod
    sync:
      manual:
        - src: 'src/**/*.js'
          dest: .
  - image: us.gcr.io/goodgamestudiotest/server
    context: server
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
deploy:
  kubectl:
    manifests:
    - k8s/*
